-- Script de creación de tablas - Proyecto Cloty
CREATE DATABASE IF NOT EXISTS cloty_db;
USE cloty_db;

CREATE TABLE usuario (id_usuario BIGINT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(120) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, rol VARCHAR(30) NOT NULL, estado BOOLEAN DEFAULT TRUE, fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE region (id_region BIGINT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(100) NOT NULL);
CREATE TABLE comuna (id_comuna BIGINT PRIMARY KEY AUTO_INCREMENT, id_region BIGINT NOT NULL, nombre VARCHAR(100) NOT NULL, FOREIGN KEY (id_region) REFERENCES region(id_region));
CREATE TABLE colegio (id_colegio BIGINT PRIMARY KEY AUTO_INCREMENT, id_usuario BIGINT, nombre VARCHAR(150) NOT NULL, email VARCHAR(120), telefono VARCHAR(30), id_comuna BIGINT, calle_numero VARCHAR(200), estado BOOLEAN DEFAULT TRUE, FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario), FOREIGN KEY (id_comuna) REFERENCES comuna(id_comuna));
CREATE TABLE apoderado (id_apoderado BIGINT PRIMARY KEY AUTO_INCREMENT, id_usuario BIGINT, rut VARCHAR(12) UNIQUE NOT NULL, nombre VARCHAR(80), apellidos VARCHAR(120), email VARCHAR(120), telefono VARCHAR(30), id_comuna BIGINT, calle_numero VARCHAR(200), estado BOOLEAN DEFAULT TRUE, FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario), FOREIGN KEY (id_comuna) REFERENCES comuna(id_comuna));
CREATE TABLE administrador (id_administrador BIGINT PRIMARY KEY AUTO_INCREMENT, id_usuario BIGINT NOT NULL, nombre VARCHAR(80), apellidos VARCHAR(120), FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario));
CREATE TABLE super_usuario (id_super_usuario BIGINT PRIMARY KEY AUTO_INCREMENT, id_usuario BIGINT NOT NULL, FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario));
CREATE TABLE curso (id_curso BIGINT PRIMARY KEY AUTO_INCREMENT, id_colegio BIGINT NOT NULL, nombre VARCHAR(50) NOT NULL, FOREIGN KEY (id_colegio) REFERENCES colegio(id_colegio));
CREATE TABLE alumno (id_alumno BIGINT PRIMARY KEY AUTO_INCREMENT, id_colegio BIGINT NOT NULL, id_apoderado BIGINT NOT NULL, rut VARCHAR(12) UNIQUE NOT NULL, nombre VARCHAR(80), apellidos VARCHAR(120), nivel VARCHAR(50), estado BOOLEAN DEFAULT TRUE, FOREIGN KEY (id_colegio) REFERENCES colegio(id_colegio), FOREIGN KEY (id_apoderado) REFERENCES apoderado(id_apoderado));
CREATE TABLE colegio_apoderado (id BIGINT PRIMARY KEY AUTO_INCREMENT, id_colegio BIGINT NOT NULL, id_apoderado BIGINT NOT NULL, FOREIGN KEY (id_colegio) REFERENCES colegio(id_colegio), FOREIGN KEY (id_apoderado) REFERENCES apoderado(id_apoderado));
CREATE TABLE tarjeta (id_tarjeta BIGINT PRIMARY KEY AUTO_INCREMENT, uid_nfc VARCHAR(100) UNIQUE NOT NULL, id_alumno BIGINT, estado VARCHAR(30) DEFAULT 'ASIGNADA', fecha_asignacion DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (id_alumno) REFERENCES alumno(id_alumno));
CREATE TABLE evento (id_evento BIGINT PRIMARY KEY AUTO_INCREMENT, id_tarjeta BIGINT NOT NULL, id_alumno BIGINT NOT NULL, id_colegio BIGINT NOT NULL, tipo_evento VARCHAR(30) NOT NULL, observacion VARCHAR(255), fecha_evento DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (id_tarjeta) REFERENCES tarjeta(id_tarjeta), FOREIGN KEY (id_alumno) REFERENCES alumno(id_alumno), FOREIGN KEY (id_colegio) REFERENCES colegio(id_colegio));
CREATE TABLE notificacion (id_notificacion BIGINT PRIMARY KEY AUTO_INCREMENT, id_evento BIGINT NOT NULL, id_apoderado BIGINT NOT NULL, leida BOOLEAN DEFAULT FALSE, fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (id_evento) REFERENCES evento(id_evento), FOREIGN KEY (id_apoderado) REFERENCES apoderado(id_apoderado));
CREATE TABLE codigo_activacion (id_codigo BIGINT PRIMARY KEY AUTO_INCREMENT, id_usuario BIGINT NOT NULL, codigo VARCHAR(6) NOT NULL, tipo VARCHAR(30) NOT NULL, usado BOOLEAN DEFAULT FALSE, fecha_expiracion DATETIME, FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario));
