# Credenciales Gmail (no subir a Git)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=usuariotidalmarzo@gmail.com
spring.mail.password=pfnx nhcc cbye pzpz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

cloty.mail.from=usuariotidalmarzo@gmail.com
cloty.mail.enabled=true
